// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrftQNksFasPsoupc5rxaW5TM-nIFYYQ',
    appId: '1:16174438438:web:06f6217f40c988fdbb6ee7',
    messagingSenderId: '16174438438',
    projectId: 'flutter-course-app-ad4ae',
    authDomain: 'flutter-course-app-ad4ae.firebaseapp.com',
    storageBucket: 'flutter-course-app-ad4ae.firebasestorage.app',
    measurementId: 'G-KYCWTQY3C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhHJJimHGeiyWUHkYvyLlztmB8qfFeSLk',
    appId: '1:16174438438:android:134d6792480121cabb6ee7',
    messagingSenderId: '16174438438',
    projectId: 'flutter-course-app-ad4ae',
    storageBucket: 'flutter-course-app-ad4ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqEfDxnDgnH9s7MSZpINamrgXTtqiomog',
    appId: '1:16174438438:ios:440fbff7dea4db02bb6ee7',
    messagingSenderId: '16174438438',
    projectId: 'flutter-course-app-ad4ae',
    storageBucket: 'flutter-course-app-ad4ae.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqEfDxnDgnH9s7MSZpINamrgXTtqiomog',
    appId: '1:16174438438:ios:440fbff7dea4db02bb6ee7',
    messagingSenderId: '16174438438',
    projectId: 'flutter-course-app-ad4ae',
    storageBucket: 'flutter-course-app-ad4ae.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYrftQNksFasPsoupc5rxaW5TM-nIFYYQ',
    appId: '1:16174438438:web:69032e419ac42cf5bb6ee7',
    messagingSenderId: '16174438438',
    projectId: 'flutter-course-app-ad4ae',
    authDomain: 'flutter-course-app-ad4ae.firebaseapp.com',
    storageBucket: 'flutter-course-app-ad4ae.firebasestorage.app',
    measurementId: 'G-ZKQNTVDL2D',
  );
}
